### PR TITLE
Migrate library/device/test/README to experimental namespace

### PR DESCRIPTION
**Pull request by Nicogene**
As suggested by @drdanz in #114 all the component has been migrated under the experimental namespace.

This is a first step towards #114

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by Nicogene** [comment]
`telemetryDeviceDumper` tested (see https://github.com/robotology-playground/yarp-telemetry/issues/115#issuecomment-812452312).

In the dumped data I noticed some strange things.

The encoders are fine:
Encoders



The velocities has strange spikes, but I suspect that are gazebo-related, they not seem corrupted data as in the past

Velocities



The accelerations are 0, but reading from the `/icubSim/left_arm/stateExt:o` I get 0 too:
```
(-28.236248898446064004 104.098246833306120607 0.114685257685557401297 14.9743547296484535991 0.0316131565940647937807 0.0729841697067017541878 0.10243839735215710951) [ok] (-6.9796794173607521472 6.46303708902291873528 3.18858403252668454186 8.09462129068094426998 2.59823309062079177423 -1.29811638110162208548 8.12032601170101031585) [ok] (0.0 0.0 0.0 0.0 0.0 0.0 0.0) [ok] (0.0 0.0 0.0 0.0 0.0 0.0 0.0) [fail] (0.0 0.0 0.0 0.0 0.0 0.0 0.0) [fail] (0.0 0.0 0.0 0.0 0.0 0.0 0.0) [fail] (1.00843141330330166028 3.06256830647855471383 -0.414156245777019149656 -21.0970765071796151346 0.0477632560715333526202 -0.0552420446141415749652 -0.0708640429945529420896) [ok] (1.00843141330330166028 3.06256830647855471383 -0.414156245777019149656 -21.0970765071796151346 0.0477632560715333526202 -0.0552420446141415749652 -0.0708640429945529420896) [ok] (1.00843141330330166028 3.06256830647855471383 -0.414156245777019149656 -21.0970765071796151346 0.0477632560715333526202 -0.0552420446141415749652 -0.0708640429945529420896) [ok] (7565168 7565168 7565168 7565168 7565168 7565168 7565168) [ok] (1718187123 1718187123 1718187123 1718187123 1718187123 1718187123 1718187123) [ok]
```
maybe the acceleration are not computed in gazebo @traversaro ?

**Comment by Nicogene** [comment]
Except for those spikes, the velocities looks fine:

immagine

**Comment by traversaro** [comment]
> maybe the acceleration are not computed in gazebo @traversaro ?

Confirmed: https://github.com/robotology/gazebo-yarp-plugins/blob/6936859f7249d234e895a97556c884159cced643/plugins/controlboard/src/ControlBoardDriverEncoders.cpp#L128 .

**Comment by Nicogene** [comment]
> Confirmed: https://github.com/robotology/gazebo-yarp-plugins/blob/6936859f7249d234e895a97556c884159cced643/plugins/controlboard/src/ControlBoardDriverEncoders.cpp#L128 .

Shall I open an issue for that?

**Pull request merged**
